### PR TITLE
Use Modern CMake

### PR DESCRIPTION
**Pull request by friendlyanon**
I started the work for this library to support clients:
 - Pulling in the project in their source tree
 - Pulling in the project from the system using `find_package` after installing

Please take a look at the work done so far and comment on my assumptions.

### CODE REVIEW

**Comment by David-Haim** [comment]
Hi there
You've made a lot of changes and I need some time to review them all. I appreciate the time and effort spend to improve this library.

A few point 
1. the thread sanitizers tests require the `-fsanitizer=thread` flag. the problem is that it requires the library (libconcurrencpp) itself to be compiled with the sanitizer flag. this is why in the original cmake had the following lines:

```
option(CONCURRENCPP_ENABLE_TSAN "Enables thread-sanitizer checks" OFF)
	if (CONCURRENCPP_ENABLE_TSAN)
		add_compile_options(-fsanitize=thread)
		add_link_options(-fsanitize=thread)
	endif()
```
and 
```
if (CONCURRENCPP_ENABLE_TSAN)
	add_subdirectory(thread_sanitizers)
endif()
```
So there's a problem there. the point of these tests is to test different functionalities with LLVM thread sanitizer.  without being compiled with it these tests are meaningless. this is also why I put them in a different folder.

2. I can see why the sandbox project looks unused but it's there for developers to play with the library. I use it a lot during development. 

3. I'm not sure the test folder should be necessarily split into a separate header and source folder, the headers files are not going to be included anywhere. Are you sure it's worth the effort?

Anyway, the rest looks good for now, still need to get to the bottom of everything :)

**Comment by friendlyanon** [comment]
Hey, thank you for the quick response.

I addressed your first two points.

Regarding the tests, the `test` directory is basically a separate project which is tightly coupled to the library one, so personally I feel like it should follow regular project structure.  
Further work is going to be required to clean things up further. I am doing something similar in https://github.com/jk-jeon/dragonbox/issues/4 mabe that can give you a better idea of what I'm thinking.  
In any case, I would like to keep touching source file contents to the absolute minimum, as that is outside the scope of this PR and they can be handled separately.

And yes, apologies for the quite intrusive changes, but I'm trying to help libraries be trivial to consume when they are:
- pulled into the source tree and included with `add_subdirectory` or `FetchContent`, or
- installed to the system and included with `find_package`.

I feel like both of these are valid use cases, with the first one gaining more prominence nowadays.

If you have any question about the changes, please do voice them along with your opinions.

**Comment by David-Haim** [comment]
OK, still need more time to dive into everything.

So first, what is the status of this PR? only tests are missing?

As for the tests, I see that you want to move to CTest, I don't disagree. there's only one thing I see with CTest is that it runs tests in parallel. I don't think It's right for us, as many tests use all the available cores. 
I'm afraid that, for example, a machine might have 4 cores, and CTest runs 4+ tests in parallel. It could be that no code will run as multi-core, the OS scheduler will pin each process' threads to just one core, hiding synchronization/ data races in the way. 

Also, there's the timer tests. I'm afraid that for example, while firing a timer, a much heavier test could start in parallel (for example, the thread pool executor test), stealing all available CPU, messing with time recording of timer tests, making the test practically fail. 

So we can move to CTest if we can guarantee that tests run in serial manner. I know it defeats the idea of CTest as a parallel test runner, but for now we have no choice. what do you think?

Also, I'll push a small new version in the next hours/tomorrow. it shouldn't break anything in your PR (no cmake changes), but make sure to rebase.

Again thanks for your effort.

**Comment by friendlyanon** [comment]
Yes, it's basically just the tests that remain.

What you want can easily be achieved with the [`RUN_SERIAL`](https://cmake.org/cmake/help/latest/prop_test/RUN_SERIAL.html) property on tests.  
See also my latest commits.

For the test part to be considered finished, source files would have to be touched, but I would like to avoid doing that in the scope of this PR.  
If you have more questions regarding steps to take after merging this PR, do not hesitate.

**Comment by David-Haim** [comment]
What do you suggest doing next to the test sources? 

(Also, it looks like I did make some conflicts to your PR, sorry. It looks like just moving these files to their right places)

**Comment by friendlyanon** [comment]
Resolved.

Also, just a tip, but you don't need to make separate branches for each release.  
You can just have the `master` branch with tags that receives commits from a `develop` branch.  
The tags will keep track of the commit at the time of release.

Regarding the tests (but also other source files where necessary), `#include`s and other paths will have to be corrected and structured in a way that allows `.cpp` files to be registered easily. I gave hints on how to achieve this in the documentation block for `add_test` in the tests' lists file.  
I believe that having tests in separate directories (and namespaces therefore) will serve as a good way to group them.

**Comment by David-Haim** [comment]
I tried to compile the latest commit with both visual studio (with built in cupport for cmake) and wsl (clang) with `cmake -S . -B build; cmake --build build` and both builds failed.
I attach both outputs 
[wsl error.txt](https://github.com/David-Haim/concurrencpp/files/5294966/wsl.error.txt)
[MSVC error.txt](https://github.com/David-Haim/concurrencpp/files/5294967/MSVC.error.txt)

**Comment by friendlyanon** [comment]
Yes, those are just the include paths in the source files not pointing to the right places.

**Comment by David-Haim** [comment]
So, will it be fixed?

**Comment by friendlyanon** [comment]
Not in this PR. Source level changes are outside the scope of it.

If you want to get an idea of what course of actions to take after the merge, you can check out the dragonbox repository linked above, which I have successfully assisted to move to modern CMake.

**Comment by David-Haim** [comment]
The question is, how can one build it now? because we can't merge something that prevents proper compilation..
Thanks

**Comment by friendlyanon** [comment]
Well, I can close this PR, you make a `dev` or `develop` branch and I can rebase the changes onto that and make a new PR.

**Comment by David-Haim** [comment]
I opened develop branch, feel free to use it :)

**Comment by friendlyanon** [comment]
Okay, going to open a new PR targeting develop.

**Pull request closed without merging**
