### PR TITLE
Make pthreads a public dependency, fix Windows CI

### PR DESCRIPTION
**Pull request by chausner**
Addresses #78 by making `Threads::Threads` a public CMake dependency and moving it out of `target_coroutine_options`.

### CODE REVIEW

**Comment by David-Haim** [comment]
It fails because now the windows version tries to link `pthreads` however this concept doesn't exist in windows (look at the if-else in target_coroutine_options). 
What is the reason it needs to move to the cmake file? can't it stay there and be made `PUBLIC`?

**Comment by chausner** [comment]
I don't think that's the problem here. `Threads::Threads` should also be available on Windows and be effectively a no-op. It compiles fine on my local Windows. It seems more like it cannot find `D:/a/concurrencpp/concurrencpp/build/tools/cmake-3.18.4-win64-x64/bin/cmake` in CI for some reason.

**Comment by chausner** [comment]
Now it fails with this error:
```
CMake Error at D:/a/concurrencpp/concurrencpp/build/tools/cmake-3.18.4-win64-x64/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  cl.
```
Looks to me like a CI problem.

**Comment by chausner** [comment]
I fixed the Windows CI issue in 38c16f9. The problem was that GitHub updated their `windows-latest` image to Visual Studio 2022 and some paths in the CI build scripts turned invalid. I updated them and also switched to the version-fixed `windows-2022` image so that future version updates won't break it again.

**Comment by David-Haim** [comment]
Hi, it looks great!
You made the PR to master, and I rebased to develop branch.
Can you resolve the conflict? 
thanks again!

**Comment by chausner** [comment]
> Hi, it looks great! You made the PR to master, and I rebased to develop branch. Can you resolve the conflict? thanks again!

Done! I see you already had fixed the CI issue in `develop` in #67. :)

**Comment by David-Haim** [comment]
It's been such busy months the last few, that I don't remember what happened to me yesterday, so February 27?! XD

**Pull request merged**
