### PR TITLE
version 0.1.6

### PR DESCRIPTION
**Pull request by David-Haim**
* memory leak fixes
* CI/CD overhaul 
* use stdlibc++ on linux by default
* library to properly export symbols when used from a shared-library
* `async_condition_variable` implementation
* `interrupted_task` as a base class for `runtime_shutdown` and `broken_task`
* readme improvements

### CODE REVIEW

**Comment by David-Haim** [comment]
@ohanar 
Hi there! long time :)
It's finally the time to release all the changes we've added in the last few months.
As you can see, the TSAN tests are failing to compile for some reason.
Can you please take a look at it? nothing has really changed since we've merged those changes to `develop`.. :/

**Comment by ohanar** [comment]
Hmm, it looks like libclang-rt is not being installed.

Adding `"libclang-rt-${version}-dev"` to https://github.com/David-Haim/concurrencpp/blob/develop/.github/actions/fetch-clang/action.yml#L42 should fix it, but I'm not sure if there was a change in packaging between versions (like with libunwind).

**Comment by David-Haim** [comment]
@ohanar 
It seems like there's no such package, tried to apply the patch [here](https://github.com/David-Haim/concurrencpp/actions/runs/4461144547)

**Comment by ohanar** [comment]
It looks like it is as I suspected, they changed the packaging like libunwind. In this case between versions 13 and 14. Instead of universally adding the package, you could add it conditionally like libunwind with
```
if (${version} -ge 14) {
    $pkgs += "libclang-rt-${version}-dev"
}
```

**Pull request merged**
