### PR TITLE
rework result_promise to only allocate on get_result

### PR DESCRIPTION
**Pull request by ohanar**
This was done to resolve leaked state that was caused when get_result isn't called. In practice, the set_* methods were usable until after get_result was called since they reset the promise's contained state (making it impossible to get the corresponding result).

I found this leak using the leak sanitizer with the result_promise_tests.

### CODE REVIEW

**Comment by David-Haim** [comment]
I don't mind the premature allocation. 
Most users who uses `result_promise` will also call `get_result`, so I don't see any real gain there.
I would prefer to just replace `bool m_result_retrieved` with a `consumer_result_state_ptr` that will be disowned when `get_result` is called.
This way the ABI and behavior do not change and the leak is fixed.

Anyway thanks for the discovery and correction.

**Comment by ohanar** [comment]
Did you mean API compatible, rather than ABI compatible? Replacing a `bool` with a `consumer_result_state_ptr` is not ABI compatible. If you want the later, you could just add a `delete m_state.release()` [here](https://github.com/David-Haim/concurrencpp/blob/master/include/concurrencpp/results/result.h#L121).

As you mentioned, `result_promise` is pretty much useless unless a user calls `get_result`. This PR as is just makes the API more closely reflect that. Namely, `static_cast<bool>(rp)` would be true if and only if there is/was a corresponding result, rather than right now which is when it is "valid" for some meaning of "valid". Additionally, it makes the class reusable, so a `result_promise` can be used again after it has been moved.

**Comment by David-Haim** [comment]
overall `result_promise` should exhibit the same behavior like `std::promise`, therefor it should be valid upon construction and invalid after move.
With `std::promise`, you can't set the result twice -  while the promise remains "valid" after setting the result/exception, the promise becomes "satisfied" and setting another result/exception will throw an `std::future_error`.
`result_promise` follows a very similar behavior - after setting the result/exception, the promise becomes empty and cannot be set again.

**Comment by David-Haim** [comment]
I fixed the leak in fcd843b53288f164eb48079b8556c207cc1348d1
I want to say that even though the PR didn't get in it doesn't mean that your work is not appreciated and important.
You helped finding a nasty leak in an edge case I had not thought about.
Thank you and feel welcome submitting more issues and PRs!

**Comment by ohanar** [comment]
So I was messing around with this, and result_promise doesn't match std::promise in a couple of ways:
1. set_* can be called before get_future for std::promise, but set_* can't be called before get_result for result_promise. This could be easily changed following your commit by removing https://github.com/David-Haim/concurrencpp/blob/fcd843b53288f164eb48079b8556c207cc1348d1/include/concurrencpp/results/result.h#L196
2. std::promise is mostly thread safe, in the sense that set_* and get_promise have well defined semantics when references to an instance are used in multiple threads. E.g.
```c++
std::promise<void> p;
std::atomic<int> setCount = 0;
std::atomic<int> exceptionCount = 0;
{
  auto setPromise = [&] {
    try {
      p.set_value();
    } catch(...) {
      return ++exceptionCount;
    }
    return ++setCount;
  };
    
  auto t1 = std::jthread(setPromise);
  auto t2 = std::jthread(setPromise);
}
assert(setCount == 1);
assert(exceptionCount == 1);
```
doesn't trigger TSAN. Fixing this is much less trivial -- first glance says it would require moving the "liveness" status of the producer and consumer into the result_state, and to stop using std::unique_ptr so that you can use atomic_exchange on the pointer stored in result_promise.

Similarly, result is missing the corresponding thread-safety guarantees that std::future provides (e.g. multiple threads can wait on a single std::future).

**Pull request closed without merging**
