### PR TITLE
Add many more build configurations to the ci

### PR DESCRIPTION
**Pull request by ohanar**
This was done by reworking the ci to make adding options easier.

Additionally, this removes any hardcoded configuration of the standard template library (superseding https://github.com/David-Haim/concurrencpp/pull/91).

Added configurations:
- macos-12 (apple-clang 14)
- clang 11 & 13 with libc++ on linux
- clang 14 & 15 with msvc's stl on windows
- clang 14 & 15 with libstdc++-11 and libstdc++-12 on linux
- clang 14 with libc++ on linux
- msvc 2019
- all existing and new configurations when built as a shared library

In total, there are now 30 build configurations.

The macos configurations are allowed to fail, as are the new shared library configurations.

### CODE REVIEW

**Comment by David-Haim** [comment]
Do you want to merge develop to this branch so we can merge this also?
great job by the way!

**Comment by ohanar** [comment]
The test suite is very prone to failure, so adding this many configurations to the CI makes it hard for things to pass. It would be good to make the test suite not so brittle.

**Comment by David-Haim** [comment]
Three things:
1. If you look closely, most tests that are failing (except one), are when shared=true, meaning it relates to the exporting PR (or so it seems). Mind running those tests locally to see if the failure reproduces?
2.  The CI originally had TSAN support, when the tests are compiled with `-DENABLE_THREAD_SANITIZER=Yes` flag with clang (see [here](https://github.com/David-Haim/concurrencpp#building-installing-and-testing) ). can you please add that as well?
3. A year ago, all timing tests finished perfectly. sleeping for 100ms on github actions vms meant sleeping for 100ms. Today, for unknown reasons, github actions behaves odd with relation to sleeping times. If I tell the application to sleep/wait for 100ms, then sometimes it sleeps for far less (like 70ms) or sometimes way more (like 200ms). I need to open a ticket for them to see what can be done.

**Comment by David-Haim** [comment]
Hi
any new on this?

**Comment by David-Haim** [comment]
The problem seems to be that the errors defined in `errors.h` weren't exported at all, which made `catch` clauses to miss them when their thrown. properly exporting them seems to solve the problem.

**Comment by ohanar** [comment]
@David-Haim Sorry, I was away getting married on my honeymoon, I'm back now. It looks like you seemed to have diagnosed the issue with the failed tests.

Regarding TSAN, it is still enabled on the newest version of clang on linux (see [here](https://github.com/David-Haim/concurrencpp/pull/95/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR72) and [here](https://github.com/David-Haim/concurrencpp/pull/95/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR80)), but I didn't include tsan in the name of the jobs since they were already getting long. I could change that if you'd like.

**Comment by David-Haim** [comment]
Congratulation on your wedding! wishing you the best!

I would actually prefer clang-15 to have 4 different configurations: [shared, static] x [with TSAN, no TSAN]. 
This way we're sure we don't miss anything (TSAN makes the execution speed way slower, and thus might even prevent some race conditions from happening in the first place!)

anyway, I pushed a few more fixes, hopefully now all problems will be solved.

**Pull request merged**
